version: '3.3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 800:800
    volumes:
      - ./static/:/static/
      - ./media/:/media/
      - /var/log/dbproject/nginx/:/var/log/nginx/
      - ./deploy/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: web
    restart: always
    depends_on:
      - rabbitmq
      - postgres
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: "dbproject.settings"
    command: >
      sh -c "
        ./manage.py migrate;
        ./manage.py compilemessages;
        ./manage.py collectstatic --noinput;
        gunicorn --bind=0.0.0.0:8000 --workers=10 --preload gamein_backend.wsgi:application;
      "
    volumes:
      - .:/code
      - ./static/:/static/
      - ./media/:/media/
      - /var/log/gamein_backend:/var/log/gamein_backend
      - cachedata:/cachec
    ports:
      - 8000:8000
    env_file:
      - .env
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=gamein
      - RABBITMQ_DEFAULT_PASS=covid19
    ports:
    - 5672:5672

volumes:
  cachedata: